### ISSUE TITLE
Newsletter form isn't showing up on button click

### ISSUE THREAD

**Issue by igormatos** [biciflow/Biciflow-Page#3]
When the user clicks "Inscrever-se na lista de espera" button is expected to open the Mailchimp popup with newsletter sign up form.

**Comment by RdrSeraphim** [comment]
Hello,

I tried testing this out, even using my own newsletter form from Mailchimp as well. I got mine to work perfectly, but yours however still fails.

Could you recreate the signup form and give me the new code for it? I have a feeling something might've changed on your form, as it's working flawlessly with mine (and the code is 90% identical).

Thank you!

**Comment by igormatos** [comment]
@vypr Sorry for the delay of the answer but someone fixed it on PR #4, but thanks for your help anyway. You can check there what was my mistake.

Thank you again.
